workflows:
  android-workflow:
    name: Fulus Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
