name: fulus
description: مدير المصاري الذكي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.1
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  # UI
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  # Utils
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
